### ISSUE TITLE
Building a distance matrix from one variable

### ISSUE THREAD

**Issue by hhagec** [fantin-mesny/Effect-of-lifestyles-on-the-genomic-composition-in-gene-families#1]
Hi,

I wanted to asses the effect of lifestyle on genome size, but the script failed in producing the distance matrix. I guess it is because the dataframe has only one column (with organisms in rows and one column with genome size).

The script didn't give any error  when assessing lifestyle effect on genes families, where in this case there are more than one column in the dataframe "data.csv" generated to build the distMatrix.csv. 

I am not able to find what to change in the script in this case,
Thanks a lot for your help

**Comment by fantin-mesny** [comment]
Hi,

Thanks for your interest in my method.

This method was developed to analyse multi-dimensional data. It is simply impossible to build a distance matrix relying on a single input column. PERMANOVA test is also only adapted to multi-dimensional data. Even though you would have other columns (such as 'geneNumber', for instance), it would not make any sense calculating pairwise genome distances on such properties. I don't see any circumstances in which you could use this method on anything other than gene counts.

Anyway, there is no need to use permutation-based testing to analyse a single variable. You can test the effect of phylogeny and lifestyle on genome sizes, using a simple linear model.
Here is how I would proceed to answer your question:
- use the 'metadata.csv' file retrieved by my script (containing the phylogenetic PCA coordinates and lifestyles).
- open it in R, and merge the dataframe to your genome sizes, so you have a 'genomeSizes' column inside
- build a linear model using the following formula:
`model <- lm(genomeSizes~PC1+PC2+lifestyle+PC1:lifestyle+PC2:lifestyle, data=yourDataFrame)`
- check that the model residuals (`residuals(model)`) are normally-distributed, either visually or using a Shapiro test
- If they are normally distributed, you can use a simple Anova test, by executing `summary(aov(model))`

I hope it helps !

**Comment by hhagec** [comment]
Great, thanks for the alternative method:)

**Comment by aberaslop** [comment]
Hi!
Thank you for this fantastic code. I was wondering if there would be a way of controlling for phylogenetic relatedness when comparing the relationship between two categories/columns such as gene content and genome size for groups of organisms with different lifestyles. For instance if you were to run: 
'model <-lm(Genome_size~Gene_content, data=dataset)'

Thank you so much once again, this method is very helpful!
